Rmr\Domain\Entity\Order:
  type: entity
  repositoryClass: Rmr\Infrastructure\Repository\OrderRepository
  table: orders
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    dateCreated:
      type: datetime
  oneToMany:
    orderProducts:
      targetEntity: OrderProduct
      mappedBy: order
      cascade: ['persist']
