Rmr\Domain\Entity\Product:
  type: entity
  repositoryClass: Rmr\Infrastructure\Repository\ProductRepository
  table: products
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
    priceTotal:
      type: decimal
      precision: 7
      scale: 2