Rmr\Domain\Entity\Product:
  product_{1..5}:
    name: <name()>
    priceTotal: '<(Money\Money::PLN(rand(10,100)))>'

Rmr\Domain\Entity\Order:
  order_1:
    ~

Rmr\Domain\Entity\OrderProduct:
  order_product_{1..2}:
    order: '@order_1'
    product: '@product_<current()>'
    quantity: <numberBetween(1,10)>

Rmr\Domain\Entity\Client:
  client_{1..5}:
    firstname: <firstname()>
    lastname: <lastname()>
    email: <email()>
