resources:
  Rmr\Application\Resource\Client\ClientResource:
    - Rmr\Ports\Operation\Client\GetOperation
    - Rmr\Ports\Operation\Client\RemoveOperation
    - Rmr\Ports\Operation\Client\ReplaceOperation
    - Rmr\Ports\Operation\Client\UpdateEmailOperation
  Rmr\Application\Resource\Client\ClientCollectionResource:
    - Rmr\Ports\Operation\ClientCollection\GetOperation
    - Rmr\Ports\Operation\ClientCollection\InsertOperation
