resources:
  Rmr\Application\Resource\Client\ClientResource:
    # GET /clients/{id}
    - Rmr\Operation\Client\GetOperation
    # DELETE /clients/{id}
    - Rmr\Operation\Client\RemoveOperation
    # PUT /clients/{id}
    - Rmr\Operation\Client\ReplaceOperation
    # PATCH /clients/{id}/email
    - Rmr\Operation\Client\UpdateEmailOperation

  Rmr\Application\Resource\Client\ClientCollectionResource:
    # GET /clients
    - Rmr\Operation\ClientCollection\GetAllOperation
    # POST /clients
    - Rmr\Operation\ClientCollection\CreateOperation

  Rmr\Application\Resource\Order\OrderCollectionResource:
    # GET /orders
    - Rmr\Operation\OrderCollection\GetAllOperation